dep 'clockwork.running' do
  requires ['monit running', 'clockwork.startable']

  setup do
    must_be_root
  end

  met? do
    (summary = shell("monit summary")) && summary[/'clockwork'/]
  end

  meet do
    shell '/etc/init.d/redis-server stop && monit start redis'
  end
end

dep 'clockwork.configured', :app_path, :user do
  setup do
    must_be_root
  end

  met? do
    "/etc/init/clockwork.conf".p.grep(/^# Generated by babushka/)
  end

  meet do
    render_erb "init/clockwork.conf.erb", :to => "/etc/init/clockwork.conf", :perms => 644
  end
end


dep 'clockwork.startable', :app_path, :user do
  requires [
               'clockwork.configured'.with(app_path, user)
           ]

  setup do
    must_be_root
  end

  met? { "/etc/monit/conf.d/clockwork.monitrc".p.exists? }
  meet do
    render_erb "monit/clockwork.monitrc.erb", :to => "/etc/monit/conf.d/clockwork.monitrc", :perms => 700
    shell "monit reload"
  end
end