dep 'confluence.installed', :version, :install_prefix, :home_directory do
  version.default!('5.6.1')
  install_prefix.default!('/usr/local/atlassian')
  home_directory.default!('/etc/confluence')

  requires [
               'jdk'.with(7),
               'atlassian.user_exists',
               'confluence'.with(version, install_prefix),
               'confluence.home_directory_set'.with(install_prefix, home_directory),
               'atlassian.permissions'.with(install_prefix, home_directory, 'confluence', 'atlassian')
           ]
end

dep 'confluence', :version, :install_prefix do
  setup do
    must_be_root
  end

  met? do
    "#{install_prefix}/confluence/bin/start-confluence.sh".p.exists?
  end

  meet do
    tar_file = "atlassian-confluence-#{version}.tar.gz"
    shell "wget http://www.atlassian.com/software/confluence/downloads/binary/#{tar_file} -P /tmp"
    shell "tar xvf /tmp/#{tar_file} -C #{install_prefix}"
    shell "mv #{install_prefix}/*confluence* #{install_prefix}/confluence"
    shell "rm /tmp/#{tar_file}"
  end
end

dep 'confluence.home_directory_set', :install_prefix, :home_directory do
  setup do
    must_be_root
  end

  met? do
    "#{install_prefix}/confluence/confluence/WEB-INF/classes/confluence-init.properties".p.grep(/Generated by babushka/)
  end

  meet do
    shell "mkdir -p #{home_directory}"
    shell "echo '# Generated by babushka' > #{install_prefix}/confluence/confluence/WEB-INF/classes/confluence-init.properties"
    shell "echo 'confluence.home=#{home_directory}' >> #{install_prefix}/confluence/confluence/WEB-INF/classes/confluence-init.properties"
  end
end