# Installs and configures monit. Like a boss.
# Taken from envato/babushka-deps@f2ddcd58fe2d76a5922a373e4c0b809b775da4f2

dep 'monit running' do
  requires 'monit'
  requires_when_unmet 'monit startable'
  met? { (status = sudo("monit status")) && status[/uptime/] }
  meet { sudo "/etc/init.d/monit start" }
end

dep 'monit', :template => 'managed'

dep 'monit startable' do
  requires 'monitrc configured', 'monit config is where we expect'
  met? { sudo "grep 'START=yes' /etc/default/monit" }
  meet { sudo "sed -i s/START=no/START=yes/ /etc/default/monit" }
end

dep 'monitrc configured', :monit_frequency, :monit_port, :monit_included_dir do
  monit_frequency.default!(30)
  monit_port.default!(9111)
  monit_included_dir.default!("/etc/monit/conf.d/*.monitrc")

  met? { sudo "grep 'Generated by babushka' /etc/monit/monitrc" }
  meet { render_erb "monit/monitrc.erb", :to => "/etc/monit/monitrc", :sudo => true, :perms => 700 }
end

dep 'monit config is where we expect' do
  met? { "/etc/default/monit".p.exists? }
  meet { shell "echo START=no >> /etc/default/monit" }
end