dep 'monit running' do
  requires %w(monit.managed monit.configured monit.startable)

  met? { (status = shell("monit status")) && status[/uptime/] }
  meet { shell "service monit stop && service monit start" }
end

dep 'monit.managed'

dep 'monit.configured', :monit_frequency, :monit_port, :monit_included_dir, :username, :password do
  monit_frequency.default!(30)
  monit_port.default!(9111)
  monit_included_dir.default!("/etc/monit/conf.d/*.monitrc")
  username.default!('monit')
  password.default('monit')

  met? { '/etc/monit/monitrc'.p.grep(/^# Generated by babushka/) }
  meet { render_erb "monit/monitrc.erb", :to => "/etc/monit/monitrc", :perms => 700 }
end

dep 'monit.startable' do
  met? { '/etc/default/monit'.p.grep(/^START=yes$/) }
  meet { shell "sed -i s/START=no/START=yes/ /etc/default/monit" }
end

dep 'register with mmonit', :mmonit_host, :mmonit_port, :username, :password  do
  mmonit_host.default('localhost')
  mmonit_port.default!('8080')
  username.default('monit')
  password.default('monit')

  met? {
    "/etc/monit/monitrc".p.grep(/set mmonit/)
  }

  meet do
    shell "echo set mmonit http://#{username}:#{password}@#{mmonit_host}:#{mmonit_port}/collector >> /etc/monit/monitrc"
  end
end