dep 'redis.running' do
  requires ['monit running', 'redis.startable']

  setup do
    must_be_root
  end

  met? do
    (summary = shell("monit summary")) && summary[/'redis'/]
  end

  meet do
    shell '/etc/init.d/redis-server stop && monit start redis'
  end
end

dep 'redis-server.managed'

dep 'redis.configured' do
  requires 'redis-server.managed'

  met? do
    "/etc/redis/redis.conf".p.grep(/^# Generated by babushka/)
  end

  meet do
    render_erb "redis/redis.conf.erb", :to => "/etc/redis/redis.conf", :perms => 644
  end
end

dep 'redis.startable', :version do
  requires 'redis.configured'

  setup do
    must_be_root
  end

  version.default!('2.6.11')

  met? { "/etc/monit/conf.d/redis.monitrc".p.exists? }
  meet do
    render_erb "monit/redis.monitrc.erb", :to => "/etc/monit/conf.d/redis.monitrc", :perms => 700
    shell "monit reload"
  end
end